### ISSUE TITLE
Create gene to phenotype mapping + integration of traits

### ISSUE THREAD

**Issue by saliksyed** [VALIS-software/SIRIUS-backend#27]
# Tasks
- [ ] Cleanup GWASCatalog data format (currently we are importing the raw field names into the JSON, we should have cleaner key names -- for example one of the key name contains a '/' and another contains a space ' ')
- [ ] Import [Human Phenotype Ontology](http://human-phenotype-ontology.github.io/downloads.html)  as trait nodes
- [ ] write a trait matching function which given a GWAS entry (Clinvar or GWASCatalog) it will figure out the right Human phenotype ontology items to map to (one GWAS entry may map to multiple phenotypes if there are several indications)
- [ ] Improve the edge storage so that id's contain the type association (e.g `E:Gsnp:Itrait`)

# Discussion
Currently, the trait nodes are generated using labels from GWASCatalog or ClinVar. We probably want to do something slightly more refined and to normalize some of the overlapping naming conventions.

I think we should use a more curated phenotype database and normalize our traits against this:
[Human Phenotype Ontology](http://human-phenotype-ontology.github.io/downloads.html)

This will probably involve some parsing, text mining and just plain data wrangling. 

Doesn't have to be done now, but we should keep this on our radar.
